language: java
jdk:
  - oraclejdk8
before_install:
  - cp HOWTO.txt dev.properties
script: mvn test -B install -P ci
after_success:
  - echo "<settings><servers><server><id>ossrh</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml
  - mvn deploy --settings ~/settings.xml
